/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms237.staff;

import static com.sun.org.apache.xml.internal.serialize.LineSeparator.Windows;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import sms237.entities.SetSchool;

/**
 *
 * @author idrice24
 */
public class EditSchool extends javax.swing.JPanel {

    /**
     * Creates new form EditSchool
     */
    public EditSchool() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Edit = new javax.swing.JButton();
        txt_schoolId = new javax.swing.JTextField();

        jLabel1.setText("Enter the Id :");

        btn_Edit.setText("Submit");
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_schoolId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_Edit)
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_schoolId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Edit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public String getEditId(){
        String n;
        
        n = txt_schoolId.getText();
           
        return n;
    }
   
    
    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
            
            System.out.println("from EditSchool values are "+getEditId());
            SetSchool st = new SetSchool();
            SetSchools sc = new SetSchools();
            
            //sc.setSchoolId(st.getSetSchoolId());
            ArrayList<SetSchool> list = sc.setSchoolTilte();
            for(int i = 0; i< list.size(); i++){
                list.get(i).getSchoolTitle();
                System.out.println("this is the output "+list.get(i).getSchoolTitle());
            }
            
            
            
            
            JFrame fr = new JFrame();
            fr.setVisible(false);
            EditSchool ed = new EditSchool();
            ed.setVisible(false);
            fr.remove(ed);
            fr.setDefaultCloseOperation(HIDE_ON_CLOSE);
            
            
            
            
            
    }//GEN-LAST:event_btn_EditActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_schoolId;
    // End of variables declaration//GEN-END:variables
}
