/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms237.staff;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Date;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static sms237.ConnectionDb.getConnections;
import sms237.entities.SetSchool;

/**
 *
 * @author idrice24
 */
public class SetSchools extends javax.swing.JFrame {

    /**
     * Creates new form SetSchool
     */
    public SetSchools() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        txt_title = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Set School");

        jLabel2.setText("School Title :");

        btn_submit.setText("submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_edit.setText("edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_cancel.setText("cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btn_submit)
                                .addGap(18, 18, 18)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_cancel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel1)))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btn_edit)
                    .addComponent(btn_cancel))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        Connection con = getConnections();
        SetSchool sch = new SetSchool();
        Date d = new Date(00,00,00);
        
        
        sch.setSchoolTitle(txt_title.getText());
         sch.setIsActive(1);
         sch.setCreatedAt(d);
         sch.setUpdatedAt(d);
         String sql ="INSERT INTO set_school(school_title, is_active, created_at, updated_at) VALUES('"+sch.getSchoolTitle()+"','"+sch.getIsActive()+"','"+sch.getCreatedAt()+"','"+sch.getUpdatedAt()+"')";
         
         try{
             Statement stmt = con.createStatement();
             stmt.executeUpdate(sql);
             JOptionPane.showConfirmDialog(null, "added succesfull!!");
         }catch(SQLException ex){
             Logger.getLogger(SetSchool.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btn_submitActionPerformed

    // getting School Id
   /* public int setSchoolId(int n){
       txt_title.setText(String.valueOf(n));
       System.out.println("from EditSchool values are--- "+n);
        return n;
    }*/
    //get school list from db
    public String setSchool(){
        EditSchool v = new EditSchool();
        System.out.println("from EditSchool values are--- "+v.getEditId());
        return v.getEditId();
    }
    public ArrayList<SetSchool> setSchoolTilte(){
        ArrayList<SetSchool> schoolAr = new ArrayList<SetSchool>();
        String sql = "SELECT * FROM set_school WHERE set_school_id ='"+setSchool()+"' ";
        Connection con = getConnections();
        Statement stm;
        ResultSet res;
        try {
            stm = con.createStatement();
            res = stm.executeQuery(sql);
            while(res.next()){
                SetSchool a = new SetSchool(res.getInt("setSchoolId"),res.getString("school_title"));
                schoolAr.add(a);
                System.out.println("values from "+res.getArray(sql));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SetSchools.class.getName()).log(Level.SEVERE, null, ex);
        }
        return schoolAr;
    }
    
    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
      EditSchool ed = new EditSchool();
      
      ed.setBackground(Color.red);
      ed.setVisible(true);
      JFrame fr = new JFrame();
      fr.setSize(400, 200);
      fr.setVisible(true);
      fr.add(ed);
    }//GEN-LAST:event_btn_editActionPerformed
    // looping in school list method
    public ArrayList<SetSchool> getListOfSchool(){
        ArrayList<SetSchool> schoolList = new ArrayList<>();
        String sql = "SELECT * FROM set_school";
        Connection conn = getConnections();
        Statement stm;
        ResultSet result;
        try{
        stm = conn.createStatement();
        result = stm.executeQuery(sql);
        SetSchool school;
        while(result.next()){
            school = new SetSchool(result.getInt("set_school_id"),result.getString("school_title"));
            schoolList.add(school);
        }
        
        }catch(SQLException ex){
            Logger.getLogger(SetSchool.class.getName()).log(Level.SEVERE, null, ex);
        }
     return schoolList;   
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetSchool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetSchool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetSchool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetSchool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetSchools().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_title;
    // End of variables declaration//GEN-END:variables

}
