/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms237.staff;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static sms237.ConnectionDb.getConnections;
import sms237.entities.Subjects;
import sms237.entities.Teachers;

/**
 *
 * @author idrice24
 */
public class Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
        setSubjectList();
        txt_tea_id.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_teaName = new javax.swing.JTextField();
        txt_gender = new javax.swing.JComboBox<>();
        txt_dob = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_wkd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reset_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        btn_submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_subject = new javax.swing.JComboBox<>();
        editTea = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_tea_id = new javax.swing.JTextField();
        TeaUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("ADD TEACHER");

        jLabel2.setText("TEACHER NAME:");

        jLabel3.setText("GENDER:");

        jLabel4.setText("DATE OF BIRTH:");

        jLabel5.setText("EMAIL:");

        jLabel6.setText("PHONE:");

        jLabel7.setText("WORKING DAYS:");

        txt_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select ", "MALE", "FEMALE", "OTHER" }));
        txt_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_genderActionPerformed(evt);
            }
        });

        reset_btn.setText("RESET");
        reset_btn.setActionCommand("RESET");
        reset_btn.setMaximumSize(new java.awt.Dimension(79, 25));
        reset_btn.setMinimumSize(new java.awt.Dimension(79, 25));
        reset_btn.setPreferredSize(new java.awt.Dimension(79, 25));
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(reset_btn);
        reset_btn.getAccessibleContext().setAccessibleName("RESET");

        btn_submit.setBackground(new java.awt.Color(51, 102, 255));
        btn_submit.setText("SUBMIT");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jScrollPane2.setViewportView(btn_submit);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel8.setText("SUBJECTS:");

        txt_subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        txt_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subjectActionPerformed(evt);
            }
        });

        editTea.setBackground(new java.awt.Color(204, 255, 204));
        editTea.setText("EDIT");
        editTea.setMaximumSize(new java.awt.Dimension(79, 25));
        editTea.setMinimumSize(new java.awt.Dimension(79, 25));
        editTea.setPreferredSize(new java.awt.Dimension(79, 25));
        editTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTeaActionPerformed(evt);
            }
        });

        jLabel9.setText("TEACH ID:");

        TeaUpdate.setBackground(new java.awt.Color(255, 255, 204));
        TeaUpdate.setText("UPDATE");
        TeaUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_teaName)
                                        .addComponent(txt_gender, 0, 266, Short.MAX_VALUE)
                                        .addComponent(txt_dob)
                                        .addComponent(txt_email)
                                        .addComponent(txt_phone)
                                        .addComponent(txt_subject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TeaUpdate)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(editTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(back)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_wkd, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_tea_id, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_teaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(txt_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_wkd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_tea_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeaUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //generateteacher list
    
    public ArrayList getTeacherList(){
        
            ArrayList<Teachers> teacherList = new ArrayList<Teachers>();
            String sql = "SELECT * FROM teachers";
            Statement stmt;
            ResultSet result;
        try {
            Connection con = getConnections();
            stmt = con.createStatement();
            result = stmt.executeQuery(sql);
            Teachers teachers;
            while(result.next()){
                teachers = new Teachers(result.getString("teacher_ful_name"),result.getString("gender"));
                teacherList.add(teachers);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return teacherList;
    }
    
    public int teacherCode(){
        ArrayList<Teachers> list = getTeacherList();
         int   teacherCodes = list.size() + 1;
        return teacherCodes;
    }
    
    
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        
if(txt_tea_id != null){
        reset_btn.setEnabled(true);
        txt_phone.setEnabled(true);
        txt_email.setEnabled(true);
        txt_dob.setEnabled(true);
        txt_subject.setEnabled(true);
        txt_teaName.setEnabled(true);
        txt_gender.setEnabled(true);
        txt_wkd.setEnabled(true);
        txt_tea_id.setEnabled(true);
        btn_submit.setEnabled(false);
        reset_btn.setEnabled(false);
        editTea.setEnabled(false);
        
        String sql = "SELECT * FROM teachers WHERE teacher_code='"+txt_tea_id.getText()+"'";
        Statement stm;
        Connection con = getConnections();
        try{
        stm = con.createStatement();
        ResultSet result;
        result = stm.executeQuery(sql);
        while(result.next()){
            Teachers teas = new Teachers();
         System.out.println("this is teach name "+teas.getTeacherFulName());
         
         txt_phone.setText(result.getString("phone"));
         txt_email.setText(result.getString("email"));
         txt_dob.setText(result.getString("dob"));
         txt_subject.setSelectedItem(result.getString("subject"));
         txt_teaName.setText(result.getString("teacher_ful_name"));
         txt_gender.setSelectedItem(result.getString("gender"));
         txt_wkd.setText("5");
        }
        } catch (SQLException ex) {
        Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }else {
        try {
            Date d = new Date(00,00,00);
            Teachers tea = new Teachers();
            tea.setCreatedAt(d);
            DateFormat formatter = new SimpleDateFormat("dd-mm-yyyy");
            java.util.Date date = formatter.parse(txt_dob.getText());
            tea.setDob(date);
            tea.setEmail(txt_email.getText());
            tea.setGender((String) txt_gender.getSelectedItem());
            tea.setIsActive(1);
            tea.setJoinDate(d);
            tea.setPhone(txt_phone.getText());
            tea.setTeacherCode("TEA00"+teacherCode());
            tea.setTeacherFulName(txt_teaName.getText());
            tea.setWorkingDays(txt_wkd.getCaretPosition());
            
            String sql = "INSERT INTO teachers(teacher_code,teacher_ful_name,gender,dob,email,phone,is_active,join_date,working_days,created_at, subject) VALUES('"+tea.getTeacherCode()+
                    "','"+tea.getTeacherFulName()+"','"+tea.getGender()+"','"+tea.getDob()+"','"+tea.getEmail()+"','"+tea.getPhone()+
                    "','"+tea.getIsActive()+"','"+tea.getJoinDate()+"','"+tea.getWorkingDays()+"','"+tea.getCreatedAt()+"','"+tea.getSubject()+"')";
            Statement stm;
            Connection con = getConnections();
            
            try {
                stm = con.createStatement();
                stm.executeUpdate(sql);
                String titleMsg = "SUBMIT SUCCESSFUL";
                Object infoMsg = "ok";
                JOptionPane.showMessageDialog(null, infoMsg, "InfoBox: "+ titleMsg, JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    }//GEN-LAST:event_btn_submitActionPerformed

    //get teacher id to edit
    public String getTeasId(String tea){
        System.out.println("this is the teacher id:"+ tea);
        return tea;
    }
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here: 
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void txt_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subjectActionPerformed
         
    }//GEN-LAST:event_txt_subjectActionPerformed

    private void txt_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_genderActionPerformed
        
    }//GEN-LAST:event_txt_genderActionPerformed

    private void editTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTeaActionPerformed

        reset_btn.setEnabled(false);
        txt_phone.setEnabled(false);
        txt_email.setEnabled(false);
        txt_dob.setEnabled(false);
        txt_subject.setEnabled(false);
        txt_teaName.setEnabled(false);
        txt_gender.setEnabled(false);
        txt_wkd.setEnabled(false);
        txt_tea_id.setEnabled(true);
        
    }//GEN-LAST:event_editTeaActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
         txt_phone.setText(null);
         txt_email.setText(null);
         txt_dob.setText(null);
         txt_subject.setSelectedItem(null);
         txt_teaName.setText(null);
         txt_gender.setSelectedItem(null);
         txt_wkd.setText(null);
    }//GEN-LAST:event_reset_btnActionPerformed

    private void TeaUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaUpdateActionPerformed
        String sql = "UPDATE teachers SET teacher_code = '"+txt_tea_id.getText()+"', phone ='"+txt_phone.getText()+"', email = '"+txt_email.getText()+
                "', dob = '"+txt_dob.getText()+"', teacher_ful_name ='"+txt_teaName.getText()+"', gender = '"+txt_gender.getSelectedItem()+"', working_days = '"+txt_wkd.getText()+
                "', subject = '"+txt_subject.getSelectedItem()+"'  WHERE (teacher_id = '"+txt_tea_id.getText()+"')";
        Statement stm;
        Connection con = getConnections();
        try{
            stm = con.createStatement();
            stm.execute(sql);
            System.out.println("update successfuly");
            
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("you have successfully updated teacher with id:"+ txt_tea_id.getText());
    }//GEN-LAST:event_TeaUpdateActionPerformed

    //calling subject list array from subject class
    public void setSubjectList(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) txt_subject.getModel();
        Subject sub = new Subject();
        ArrayList<Subjects> list = sub.listSubject();
        for(int i = 0; i<list.size(); i++){
            model.insertElementAt(list.get(i).getSbname(), i);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TeaUpdate;
    private javax.swing.JButton back;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton editTea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton reset_btn;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JComboBox<String> txt_gender;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JComboBox<String> txt_subject;
    private javax.swing.JTextField txt_teaName;
    private javax.swing.JTextField txt_tea_id;
    private javax.swing.JTextField txt_wkd;
    // End of variables declaration//GEN-END:variables
}
